### ISSUE TITLE
Test generate empty figure

### ISSUE THREAD

**Issue by petrusboniatus** [virtualritz/libfive-rs#6]
I encountered the same problem with 3d and 2d figures.

```bash
pedro@fedora:~/git/libfive-rs$ cargo test test_2d
   Compiling libfive-sys v0.2.0 (/home/pedro/git/libfive-rs/libfive-sys)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.75s
     Running unittests src/lib.rs (target/debug/deps/libfive-597a571c2caddf89)

running 1 test
test test_2d ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.01s

     Running unittests src/lib.rs (target/debug/deps/libfive_sys-0d6495476433d31d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 17 filtered out; finished in 0.00s
```

```bash
pedro@fedora:~/git/libfive-rs$ cat libfive/circle.svg 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
 width="4" height="4" id="libfive">
```

**Comment by virtualritz** [comment]
Indeed. It seems export (or something else) is completely broken.

I can also not get 0.1.3 to build any more on my Linux box (some C++ issue with the actual libfive and a missing header). So it's difficult to triage this.

@julianschuler did your fork produce the files (with content)?

**Comment by julianschuler** [comment]
I just ran the test and both files produced by them are empty (except their header). I think the issue here is that the resolution exposed by the changed libfive API is now the inverse of the smallest feature size. Changing the tests to use a resolution of `10.0` and `100.0` instead of `0.1` and `0.01` respectively seems to resolve this.

I will open up a PR with a fix soon. @virtualritz Do we want to keep the current notion of the resolution as the smallest feature size or should we adapt it to the inverse to align with the API provided by libfive?

**Comment by virtualritz** [comment]
> I will open up a PR with a fix soon.

Awesome!

>  Do we want to keep the current notion of the resolution as the smallest feature size or should we adapt it to the inverse to align with the API provided by `libfive`?

@julianschuler, I would think we adapt to the `libfive` API and have this mean feature size.

**Comment by julianschuler** [comment]
Just to clarify, the `libfive` API now uses **the inverse** of the minimum feature size, not the minimum feature size itself. @virtualritz Do you still want to adhere to the libfive API?

**Comment by virtualritz** [comment]
@julianschuler Yes. I did read your first message. :grin:

I'm ok with this. In fact, this is kinda what happened in VFX. In the old days we had *shading rate*, which is the size of the smallest element in pixels squared. And nowadays it's *shading samples*, the inverse, i.e. the number of samples per pixel.

I understand that in `libfive`, too, this measure is now the number of pixels/voxels a unit length gets subdivided by.

**Comment by virtualritz** [comment]
`v0.3.1` is published with updated docs.

`v0.2` and `v0.3` were yanked.
